### ISSUE TITLE
Add labels for all controls (Events, Amount, Donations)

### ISSUE THREAD

**Issue by quayew** [WomensCodingCircle/jcc-app#7]

**Comment by JingqunMa** [comment]
Is this for the index page?  otherwise I think column for each table is labeled

**Comment by ntj** [comment]
It would be a change in app/templates/landing_page.html. You're right, but the select elements to pick an event, to select a person and the input field to enter an amount are not labeled yet. One could also head a small heading, maybe wrapped with a <h3> element right above the table to indicate the table is about donations.
